policy_path: "../../../../resources/policies/policy_1.pt"
default_angles: [0.1,0.8,-1.5,-0.1,0.8,-1.5,0.1,1.0,-1.5,-0.1,1,-1.5]
lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 16
num_obs: 68
action_scale: 0.25
